version: 2.1

orbs:
  node: circleci/node@5.0.2 # orb version

jobs:
  test:
    executor:
      name: node/default
      tag: '14.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn eslint src/**
          name: Run eslint
      - run:
          command: yarn test:coveralls
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - test:
          context:
            - coveralls
